version: "3.8"
services:
  mongo44:
    container_name: mongo44
    build: ./databases/mongo44/
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: infocenter
      MONGO_INITDB_ROOT_PASSWORD: infocenter6148
      MONGO_INITDB_DATABASE: admin
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - "27017:27017"
    volumes:
      - 'dck-mongo44:/data/db'
    networks:
      - dck

  php56:
    container_name: php56
    build: ./php56/
    links:
      - mongo44
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html/
      - ./:/usr/local/apache2/htdocs
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    depends_on:
      - mongo44
    networks:
      - dck
    working_dir: /var/www/html/
  
networks:
  dck:
    driver: bridge

volumes:
  dck-mongo44:
    driver: local