services:
  mongo44:
    container_name: mongo44
    image: arm64v8/mongo:4.4
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: infocenter
      MONGO_INITDB_ROOT_PASSWORD: infocenter6148
      MONGO_INITDB_DATABASE: admin
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - "27017:27017"
    volumes:
      - 'dck-mongo44:/data/db'
    networks:
      - dck
  
networks:
  dck:
    driver: bridge

volumes:
  dck-mongo44:
    driver: local