services:
  mongo:
    container_name: mongo
    image: mongo:4.4
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: infocenter
      MONGO_INITDB_ROOT_PASSWORD: infocenter6148
      MONGO_INITDB_DATABASE: admin
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - "27017:27017"
    volumes:
      - 'dck-mongo:/data/db'
      - ./novosdiamantes/mongo-init:/docker-entrypoint-initdb.d
    networks:
      - dck
  
networks:
  dck:
    driver: bridge

volumes:
  dck-mongo:
    driver: local