[supervisord]
nodaemon=true

[program:php-fpm]
command=/usr/local/sbin/php-fpm --fpm-config /usr/local/etc/php-fpm.conf
autostart=true
autorestart=true

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
